version: "3"

services:
  webnodejs:
    build: .
    # nodemon will watch the files in the directory in which nodemon was started, 
    # and if any files change, nodemon will automatically restart your node application.
    # https://www.npmjs.com/package/nodemon/v/1.11.0
    command: nodemon -L --inspect=0.0.0.0:5858
    
    # Sincroniza la carpeta local . del proyecto con la carpeta de la imagen /code
    volumes:
      - .:/code
    
    ports:
      - "8000:8000"
      - "5858:5858"